"""
Django settings for dataentery project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-ciu25#(k=3wy_p-!#!u4+2-5%&_f90hy1*n_6$y3##^(avafk1')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost,0.0.0.0', cast=Csv())


# Application definition

INSTALLED_APPS = [
    # تطبيقات المدير والأساسية
    'jazzmin',  # يجب أن يكون قبل admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # تطبيقات المشروع
    'stitec',  # تطبيق المشروع الرئيسي
    
    # تطبيقات الطرف الثالث
    'rest_framework',  # دعم REST API
    'corsheaders',  # دعم CORS
    'django_extensions',  # أدوات إضافية
    'import_export',  # استيراد وتصدير البيانات
    'django_bootstrap5',  # دعم Bootstrap 5
    'widget_tweaks',  # تخصيص النماذج في القوالب
    'debug_toolbar',  # شريط أدوات التصحيح للتطوير
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # إضافة middleware للملفات الثابتة في الإنتاج
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # إضافة middleware لدعم CORS
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # تم تعطيل middleware لشريط أدوات التصحيح
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'dataentery.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # إضافة مجلد القوالب
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dataentery.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# استخدام قيمة DATABASE_URL من ملف .env أو متغيرات البيئة
DATABASE_URL = config('DATABASE_URL', default=None)

# إعداد قاعدة البيانات باستخدام متغيرات البيئة المنفصلة
# هذا النهج يعطي مرونة أكبر خصوصاً عند استخدام منصات مثل Render
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='da_db'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default='52640'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
    }
}

# في حال توفر DATABASE_URL، استخدمه بدلاً من الإعدادات المنفصلة
if DATABASE_URL:
    DATABASES['default'] = dj_database_url.config(default=DATABASE_URL, conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# تكوين WhiteNoise لضغط وخدمة الملفات الثابتة
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# وسائط التحميل
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# إعدادات الأمان
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# تشغيل HTTPS فقط في الإنتاج
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === إعدادات Django Debug Toolbar ===
# تم تعطيل شريط أدوات التصحيح
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: False,  # تعطيل الشريط على جميع الصفحات
}
INTERNAL_IPS = [
    '127.0.0.1',
]

# === إعدادات Django REST Framework ===
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# === إعدادات CORS ===
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# === إعدادات Jazzmin ===
JAZZMIN_SETTINGS = {
    "site_title": "نظام المحاسبة",
    "site_header": "نظام المحاسبة والإدارة",
    "site_brand": "نظام ERP",
    "site_logo": None,
    "welcome_sign": "مرحباً بك في نظام إدارة المحاسبة",
    "copyright": "حقوق الملكية © 2025",
    "search_model": "stitec.Product",
    "user_avatar": None,
    # الألوان والنمط
    "theme": "default",
    "dark_mode_theme": None,
    "site_icon": None,
    # الوصول السريع للنماذج
    "topmenu_links": [
        {"name": "الرئيسية", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "الموقع", "url": "/", "new_window": True},
    ],
}
