# Generated by Django 5.2 on 2025-05-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stitec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='package_tension',
        ),
    ]
